CREATE TABLE poems (
  id SERIAL PRIMARY KEY,
  poem_text TEXT NOT NULL,
  author_name VARCHAR(255) NOT NULL,
  upvotes INT NOT NULL DEFAULT 0,
  downvotes INT NOT NULL DEFAULT 0,
  date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
